Test
ilb/devapplications pull request #8
Opened 2021-03-29 14:38 UTC by CiberLord

Создал функцию для работы со вторым шаблоном

2021-03-30 03:35 UTC, slavb18 requested changes
Нужно восстановить удаленные файлы

![image](https://user-images.githubusercontent.com/2534896/112929918-7014d700-912a-11eb-87f8-943ddf686bf8.png)

2021-03-30 08:30 UTC, CiberLord commented
Хорошо, я понял

2021-03-31 04:19 UTC, merged

2021-03-31 05:53 UTC, slavb18 commented
Зайдите в чат devapplications https://t.me/joinchat/JjZHp8vJHY1iNDky

2021-03-31 07:04 UTC, CiberLord commented
Хорошо, зашел

ср, 31 мар. 2021 г. в 08:53, slavb18 ***@***.***>:

> Зайдите в чат devapplications https://t.me/joinchat/JjZHp8vJHY1iNDky
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ilb/devapplications/pull/8#issuecomment-810787312>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMSKLPGKE73W6GM7R6SXFJLTGK2G7ANCNFSM4Z7W7YLQ>
> .
>